Clang format workflow
waterloo-rocketry/cansw_processor_canards pull request #28
Opened 2024-11-12 01:41 UTC by JasonBrave

2024-11-12 03:58 UTC, Armaan-Sengupta commented
im not gonna lie, idk how this works at all, this is too SWE for me, lmao, ill approve it if christine does, I trust u christine 👍.

2024-11-18 16:37 UTC, celery6 requested changes

2024-11-18 16:39 UTC, JasonBrave commented on scripts/format.sh
> +${CLANG_FORMAT:-clang-format} -i --style=file:STM32Cube/src/lib/rocketlib/.clang-format STM32Cube/src/application/*/*.c STM32Cube/src/application/*/*.h STM32Cube/src/drivers/*/*.c STM32Cube/src/drive
:face:

2024-11-18 16:50 UTC, celery6 approved these changes

2024-11-18 16:51 UTC, merged