initilized UART driver header file with peripheral definitions and fu…
waterloo-rocketry/cansw_processor_canards pull request #37
Opened 2024-11-30 05:05 UTC by punchdii

**UART Module Header File:**

- Defines enums for different UART channels(for serial debugging and IMU)

- Defines public interfaces

2024-12-04 02:40 UTC, celery6 commented
notice the commit failed to pass the formatting check:
![image](https://github.com/user-attachments/assets/26e31f5b-280b-4065-a5a5-2fc8dd2d61c8)

last paragraph in this explains how to use clang-format to correctly auto-format your code so it passes the check: https://docs.waterloorocketry.com/onboarding-tutorials/firmware-how-to/clang-format.html#running-clang-format-on-a-can-firmware-repository

2024-12-23 11:02 UTC, Joe-Joe-Joe-Joe requested changes
Please address the comments in the gdoc

2024-12-23 11:02 UTC, Joe-Joe-Joe-Joe commented on src/drivers/uart/uart.h
> +
`uart_read` ?

2025-01-23 03:29 UTC, celery6 commented
replaced old vn usart config with movella uart8 in the .ioc file.

2025-01-24 01:56 UTC, celery6 commented
admin abuse merging because github pipelines bokrne

2025-01-24 01:56 UTC, merged