Header file for state estimation
waterloo-rocketry/cansw_processor_canards pull request #40
Opened 2024-12-17 03:55 UTC by Hany25

2024-12-20 05:43 UTC, celery6 commented
![image](https://github.com/user-attachments/assets/c055231f-cb63-4a76-bfef-278e39306a5a)
(in the google doc comment i referenced this as an "unwritten rule" but it is apparently written lol)

2024-12-22 17:03 UTC, Joe-Joe-Joe-Joe commented
Please see/address the comments in the google doc

2024-12-22 22:46 UTC, FinnBreu commented on src/application/state_estimation/state_estimation.h
> +} controller_state_t;
estimator_state_t

2024-12-22 22:47 UTC, FinnBreu commented on src/application/state_estimation/state_estimation.h
> +    vectors_3axis attitude;
attitude is quaternion with 4 elements

2025-01-11 03:55 UTC, celery6 requested changes

2025-01-11 03:55 UTC, celery6 commented on src/application/state_estimation/state_estimation.h
> +} vectors_3axis;
https://github.com/waterloo-rocketry/cansw_processor_canards/pull/44
added project-wide vector type, pls use this for consistency and lmk if it needs changes

2025-01-20 02:39 UTC, celery6 requested changes
i added more detail to the design doc section and checked all the requirements in that table are met (so far). Just these minor naming changes (easier to do that now than later) then lgtm!

2025-01-20 02:39 UTC, celery6 commented on src/application/state_estimation/state_estimation.h
> +} Estimator_controller_state_t;
this is defined by controller module so it shouldnt be duplicated here
https://github.com/waterloo-rocketry/cansw_processor_canards/pull/34/files

2025-01-20 02:39 UTC, celery6 commented on src/application/state_estimation/state_estimation.h
> +#define can_output_counter 0;
this info is private to estimator module right? if so, it shouldn't be revealed in this header file

2025-01-22 06:31 UTC, celery6 approved these changes
names should be `camel_case` ie everything is lowercase
but thats a nitpick at this point, fix that in some later pr tbh LGTM!!!

2025-01-22 06:31 UTC, merged