Add AltIMU10 header file with sensor data structures and function protocols
waterloo-rocketry/cansw_processor_canards pull request #42
Opened 2024-12-19 21:40 UTC by arpitarunkumaar

Design details are laid out in the module design doc under the AltIMU section [here](https://docs.google.com/document/d/1OokvdQ8c74xzt_znfmBUrUzJ5vtqvndMz0l9xxN98dY/edit?tab=t.0#heading=h.mxwft7budhpj). 

**Comments:**
- We understand your point about keeping register addresses local to AltIMU_Init() since they are only needed within that function. Making them global is unnecessary as AltIMU_Init() is called by the reset function anyway. We believe this local approach is efficient and avoids unnecessary and excessive clutter in the global defines section. Let us know if you feel otherwise or have any concerns.
- Do we need the externs to the protocol handlers?

2024-12-22 23:41 UTC, celery6 requested changes
also added some comments in gdoc.

i like how clean this is - gg for great clarity

2024-12-22 23:41 UTC, celery6 commented on src/drivers/altimu-10/altimu-10.h
> +} altimu_imu_address_info;
does this data need to be revealed in this header file? what else uses it

2024-12-22 23:41 UTC, celery6 commented on src/drivers/altimu-10/altimu-10.h
> +w_status_t altimu_init(I2C_HandleTypeDef *hi2c);
i2c is taken care of by the i2c module - see comments in gdoc

2024-12-22 23:41 UTC, celery6 commented on src/drivers/altimu-10/altimu-10.h
> +void altimu_delay_ms(uint32_t ms);
should these be revealed in this header file? seems like only the altimu module will use this?

2024-12-22 23:41 UTC, celery6 commented on src/drivers/altimu-10/altimu-10.h
> +extern UART_HandleTypeDef huart2; // UART handler
wont need these since these are taken care of by the respective device driver modules for i2c, uart (we dont have anything on spi yet)

2024-12-23 05:36 UTC, Joe-Joe-Joe-Joe commented on src/drivers/altimu-10/altimu-10.h
> +} altimu_magnetometer_data;
I don't think so. Here, the data is going to come out in a fraction of full scale. The particular IMU module should then math that into a float by applying the correct conversion factor (data / 2^16 * 1000 dps) If your full scale is +/- 1000 dps.  By doing this we ensure all sensor data is provided in a common format at the source. 

I think every "vector" that we pass around should be floating point type by convention, and that will prevent accidental integer math errors.

2024-12-23 10:50 UTC, Joe-Joe-Joe-Joe requested changes

2024-12-23 10:50 UTC, Joe-Joe-Joe-Joe commented on src/drivers/altimu-10/altimu-10.h
> +altimu_accelerometer_data altimu_get_acc_data(void);
See my comments in the doc, I think these should be returning status codes and modifying pointers rather than returning structs

2024-12-23 10:50 UTC, Joe-Joe-Joe-Joe commented on src/drivers/altimu-10/altimu-10.h
> +void altimu_delay_ms(uint32_t ms);
I don't see this function in the gdoc, what is its purpose? I don't know what convention has been adopted but our delay function should be common (such as freeRTOS `vTaskDelay`) across modules

2024-12-23 10:50 UTC, Joe-Joe-Joe-Joe commented on src/drivers/altimu-10/altimu-10.h
> +#define ALTIMU_EXPECTED_WHO_AM_I 0x6C // Expected WHO_AM_I value
Why do these need to be exposed in the header? Would one not simply call `altimu_check_sanity` and have the register comparisons happen under the hood?

2024-12-23 10:50 UTC, Joe-Joe-Joe-Joe commented on src/drivers/altimu-10/altimu-10.h
> +} altimu_barometer_data;
Do the device registers for pressure and temp store data as a float? Otherwise I assume these would be ints like the IMU data?

2025-02-06 14:15 UTC, FinnBreu commented on src/drivers/altimu-10/altimu-10.h
> +    float temperature; // celsius
We discussed a few weeks ago that the temperature measurement would not be reliable: the sensor is on a board inside the electronics bay, which heats up more than air temp outside the rocket

2025-02-06 14:20 UTC, celery6 commented on src/drivers/altimu-10/altimu-10.h
> +    float temperature; // celsius
this module is a device driver. its purpose is to allow other ppl to collect all the data possible. IMU Handler will choose whether to ignore temperature

2025-02-06 23:55 UTC, FinnBreu approved these changes

2025-02-07 00:06 UTC, merged